# Generated by Django 4.2.20 on 2025-12-29 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR"),
                    ("MANAGER", "Manager"),
                    ("EMPLOYEE", "Employee"),
                ],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
    ]
