# Generated by Django 4.2.20 on 2025-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR"),
                    ("MANAGER", "Manager"),
                    ("EMPLOYEE", "Employee"),
                    ("SUPERADMIN", "Super Admin"),
                ],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
    ]
