# Generated by Django 4.2.20 on 2025-12-31 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_shift"),
        ("accounts", "0006_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.shift",
            ),
        ),
    ]
