# Generated by Django 4.2.20 on 2025-12-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_shift"),
        ("accounts", "0007_profile_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.company",
            ),
        ),
    ]
