# Generated by Django 4.2.20 on 2025-12-31 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_approve_attendance", models.BooleanField(default=False)),
                ("can_view_team", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("can_self_access", models.BooleanField(default=True)),
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.role"
                    ),
                ),
            ],
        ),
    ]
