# Generated by Django 4.2.20 on 2026-01-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_profile_role_profile_group_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="group_role",
        ),
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HR", "HR"),
                    ("MANAGER", "Manager"),
                    ("EMPLOYEE", "Employee"),
                    ("SUPERADMIN", "Super Admin"),
                ],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
    ]
