# Generated by Django 4.2.20 on 2026-01-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_profile_group_role_profile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolepermission",
            name="role",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="role",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="RolePermission",
        ),
    ]
