# Generated by Django 4.2.20 on 2026-01-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_rolepermission_role_remove_profile_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
