# Generated by Django 4.2.20 on 2026-01-21 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0014_alter_profile_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="team_leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tl_team_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
