# Generated by Django 4.2.20 on 2026-02-09 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0029_branch"),
        ("accounts", "0015_profile_team_leader"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.branch",
            ),
        ),
    ]
