# Generated by Django 4.2.20 on 2026-02-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_profile_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="accounts.profile",
            ),
        ),
    ]
