# Generated by Django 4.2.20 on 2026-02-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0029_branch"),
        ("accounts", "0017_profile_reports_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="shift",
        ),
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.company",
            ),
        ),
    ]
