# Generated by Django 4.2.20 on 2026-02-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_profile_manager_profile_shift"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="shift",
        ),
    ]
