# Generated by Django 4.2.20 on 2026-02-10 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0031_branch"),
        ("accounts", "0021_remove_profile_branch_remove_profile_reports_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_staff",
                to="attendance.branch",
            ),
        ),
    ]
