# Generated by Django 4.2.20 on 2026-02-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_profile_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
