# Generated by Django 4.2.20 on 2025-12-30 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0004_alter_company_name_attendancepolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("old_check_in", models.DateTimeField(blank=True, null=True)),
                ("old_check_out", models.DateTimeField(blank=True, null=True)),
                ("new_check_in", models.DateTimeField(blank=True, null=True)),
                ("new_check_out", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
