# Generated by Django 4.2.20 on 2025-12-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendancecorrection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancecorrection",
            name="new_check_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancecorrection",
            name="new_check_out",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancecorrection",
            name="old_check_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancecorrection",
            name="old_check_out",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
