# Generated by Django 4.2.20 on 2026-01-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="applied_at",
            field=models.DateTimeField(),
        ),
    ]
