# Generated by Django 4.2.20 on 2026-01-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_leave_applied_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
