# Generated by Django 4.2.20 on 2026-01-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leave",
            name="old_from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="old_to_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
