# Generated by Django 4.2.20 on 2026-01-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_leave_is_updated_leave_old_from_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
