# Generated by Django 4.2.20 on 2026-01-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0014_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="can_view_reports",
            field=models.BooleanField(default=False),
        ),
    ]
