# Generated by Django 4.2.20 on 2026-01-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0016_profile_task_remove_attendancecorrection_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_out",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
