# Generated by Django 4.2.20 on 2026-01-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0017_alter_attendance_check_in_alter_attendance_check_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancecorrection",
            name="new_check_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancecorrection",
            name="new_check_out",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
