# Generated by Django 4.2.20 on 2026-01-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("attendance", "0018_alter_attendancecorrection_new_check_in_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_approve_attendance", models.BooleanField(default=False)),
                ("can_view_team", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=False)),
                ("can_self_access", models.BooleanField(default=False)),
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_permissions",
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
