# Generated by Django 4.2.20 on 2026-01-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0019_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="applied_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
