# Generated by Django 4.2.20 on 2026-01-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0020_leave_applied_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancecorrection",
            name="old_check_in",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="old_check_out",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
