# Generated by Django 4.2.20 on 2026-01-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("attendance", "0021_attendancecorrection_old_check_in_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Permission",
            new_name="RolePermission",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
