# Generated by Django 4.2.20 on 2026-01-21 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0022_rename_permission_rolepermission_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.company",
            ),
        ),
    ]
