# Generated by Django 4.2.20 on 2026-01-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0023_shift_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancepolicy",
            name="week_off_days",
            field=models.CharField(
                default="6",
                help_text="Comma separated days (0=Mon, 6=Sun)",
                max_length=50,
            ),
        ),
    ]
