# Generated by Django 4.2.20 on 2026-01-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0024_attendancepolicy_week_off_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancepolicy",
            name="week_off_days",
            field=models.CharField(
                default="6", help_text="Example: '5,6' for Sat-Sun", max_length=50
            ),
        ),
    ]
