# Generated by Django 4.2.20 on 2026-01-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0025_alter_attendancepolicy_week_off_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancepolicy",
            name="week_off_days",
            field=models.CharField(default="6", max_length=50),
        ),
    ]
