# Generated by Django 4.2.20 on 2026-01-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("attendance", "0026_alter_attendancepolicy_week_off_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolepermission",
            name="role",
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="can_approve_leave",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="can_manage_shifts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="auth.group",
            ),
        ),
    ]
