# Generated by Django 4.2.20 on 2026-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0027_remove_rolepermission_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
