# Generated by Django 4.2.20 on 2026-02-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0029_branch"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
