# Generated by Django 4.2.20 on 2026-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0031_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(default="#", max_length=255),
        ),
    ]
