# Generated by Django 4.2.20 on 2026-02-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0033_task_priority_task_progress_alter_task_assigned_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_file",
            field=models.FileField(
                blank=True, null=True, upload_to="task_submissions/"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completion_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
