# Generated by Django 4.2.20 on 2026-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0035_taskattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="rejection_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Submitted"),
                    ("Verified", "Verified"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
