# Generated by Django 4.2.20 on 2026-02-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0036_task_rejection_note_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
