# Generated by Django 4.2.20 on 2026-03-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0037_task_rejected_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Branch GPS Latitude", null=True
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Branch GPS Longitude", null=True
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="radius",
            field=models.IntegerField(
                default=50, help_text="Allowed check-in radius in meters"
            ),
        ),
    ]
